# Generated by Django 5.1 on 2024-08-12 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.CharField(max_length=100, unique=True)),
                ('ProductTitle', models.CharField(max_length=255)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductDescription', models.TextField()),
                ('MainImageURL', models.URLField()),
                ('AllImagesURLs', models.JSONField()),
                ('CategoryID', models.CharField(max_length=100)),
                ('CategoryName', models.CharField(max_length=255)),
                ('ItemSpecifications', models.JSONField()),
                ('EndTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryID', models.CharField(max_length=100, unique=True)),
                ('CategoryName', models.CharField(max_length=255)),
                ('ParentCategoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bid.category')),
            ],
        ),
    ]
