# Generated by Django 5.1 on 2024-08-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0006_alter_category_parentcategoryid_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('sold', 'Sold')], default='live', max_length=10),
        ),
    ]
