# Generated by Django 5.1 on 2024-08-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0008_alter_order_status_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
