# Generated by Django 5.1 on 2024-09-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0011_bid_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
