# Generated by Django 5.1 on 2024-09-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
