# Generated by Django 5.1 on 2024-09-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0016_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
