# Generated by Django 5.1 on 2024-08-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ParentCategoryID',
        ),
    ]
